DROP TABLE IF EXISTS TB_ENTREGA;
DROP TABLE IF EXISTS TB_PRODUTO;
DROP TABLE IF EXISTS TB_CLIENTE;


CREATE TABLE TB_CLIENTE (
    ID_CLIENTE SERIAL PRIMARY KEY,
    CODIGO_CLIENTE VARCHAR(50) UNIQUE, -- Gerado automaticamente via DAO (Sigla + ID)
    NOME VARCHAR(100) NOT NULL,
    DOCUMENTO VARCHAR(20) NOT NULL UNIQUE,
    CEP VARCHAR(10),
    ESTADO VARCHAR(2),
    CIDADE VARCHAR(100),
    BAIRRO VARCHAR(100),
    RUA VARCHAR(100),
    NUMERO_CASA INT
);

CREATE TABLE TB_PRODUTO (
    ID_PRODUTO SERIAL PRIMARY KEY,
    CODIGO_PRODUTO VARCHAR(50) UNIQUE,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255),
    PRECO_PRODUTO NUMERIC(10, 2) NOT NULL,
    QUANTIDADE BIGINT DEFAULT 0
);

CREATE TABLE TB_ENTREGA (
    ID_ENTREGA SERIAL PRIMARY KEY,
    CODIGO_PEDIDO VARCHAR(50) UNIQUE, -- Código de rastreio (Ex: ENC202500001)

    ID_REMETENTE INT NOT NULL,
    ID_DESTINATARIO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,

    QTD_PEDIDA INT NOT NULL DEFAULT 1,
    DATA_ENVIO DATE NOT NULL,
    DATA_ENTREGA DATE,
    TRANSPORTADORA VARCHAR(100),
    VALOR_FRETE NUMERIC(10, 2) DEFAULT 0.00,
    STATUS VARCHAR(20) DEFAULT 'PENDENTE', -- PENDENTE, REALIZADA, CANCELADA

    -- Chaves Estrangeiras para garantir a Integridade Referencial
    CONSTRAINT FK_REMETENTE FOREIGN KEY (ID_REMETENTE) REFERENCES TB_CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_DESTINATARIO FOREIGN KEY (ID_DESTINATARIO) REFERENCES TB_CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO)
);