DROP TABLE IF EXISTS TB_ENTREGA;
DROP TABLE IF EXISTS TB_PRODUTO;
DROP TABLE IF EXISTS TB_CLIENTE;

-- Tabela de Clientes (Unificada PF e PJ)
CREATE TABLE TB_CLIENTE (
    ID_CLIENTE SERIAL PRIMARY KEY,
    CODIGO_CLIENTE VARCHAR(50) UNIQUE,
    NOME VARCHAR(100) NOT NULL,
    DOCUMENTO VARCHAR(20) NOT NULL UNIQUE,
    ESTADO VARCHAR(50),
    CIDADE VARCHAR(100),
    BAIRRO VARCHAR(100),
    RUA VARCHAR(100),
    NUMERO_CASA INT
);

-- Tabela de Produtos
CREATE TABLE TB_PRODUTO (
    ID_PRODUTO SERIAL PRIMARY KEY,
    CODIGO_PRODUTO VARCHAR(50) UNIQUE,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255),
    PRECO_PRODUTO NUMERIC(10, 2),
    QUANTIDADE BIGINT
);

-- Tabela de Entregas (Agora com Remetente e Destinatário)
CREATE TABLE TB_ENTREGA (
    ID_ENTREGA SERIAL PRIMARY KEY,
    CODIGO_PEDIDO VARCHAR(50) UNIQUE,

    ID_REMETENTE INT NOT NULL,
    ID_DESTINATARIO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,

    DATA_ENVIO DATE,
    DATA_ENTREGA DATE,
    TRANSPORTADORA VARCHAR(100),
    VALOR_FRETE NUMERIC(10, 2),
    STATUS VARCHAR(20) DEFAULT 'PENDENTE',

    -- Chaves Estrangeiras
    CONSTRAINT FK_REMETENTE FOREIGN KEY (ID_REMETENTE) REFERENCES TB_CLIENTE(ID_CLIENTE) ON DELETE CASCADE,
    CONSTRAINT FK_DESTINATARIO FOREIGN KEY (ID_DESTINATARIO) REFERENCES TB_CLIENTE(ID_CLIENTE) ON DELETE CASCADE,
    CONSTRAINT FK_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO) ON DELETE CASCADE
);