
CREATE TABLE TB_CLIENTE (
    ID_CLIENTE        SERIAL        PRIMARY KEY,
    CODIGO_CLIENTE    VARCHAR(20)   NOT NULL UNIQUE,
    NOME              VARCHAR(100)  NOT NULL,
    CPF               CHAR(14)      NOT NULL UNIQUE,
    DATA_NASCIMENTO   DATE          NOT NULL,
    EMAIL             VARCHAR(150)  NOT NULL UNIQUE,
    SENHA             VARCHAR(200)  NOT NULL
);


CREATE TABLE TB_ENDERECO (
    ID_ENDERECO   SERIAL        PRIMARY KEY,
    ID_CLIENTE    INTEGER       NOT NULL,
    ESTADO        CHAR(2)       NOT NULL,
    CIDADE        VARCHAR(100)  NOT NULL,
    BAIRRO        VARCHAR(100)  NOT NULL,
    RUA           VARCHAR(100)  NOT NULL,
    CEP           CHAR(10)      NOT NULL,
    NUMERO_CASA   INTEGER       NOT NULL,

    CONSTRAINT FK_ENDERECO_CLIENTE
        FOREIGN KEY (ID_CLIENTE)
        REFERENCES TB_CLIENTE (ID_CLIENTE)
);


CREATE TABLE TB_PRODUTO (
    ID_PRODUTO       SERIAL         PRIMARY KEY,
    CODIGO_PRODUTO   CHAR(30)       NOT NULL UNIQUE,
    NOME_PRODUTO     VARCHAR(100)   NOT NULL,
    DESCRICAO        VARCHAR(600)   NOT NULL,
    PRECO_PRODUTO    NUMERIC(10,2)  NOT NULL,
    QUANTIDADE       INTEGER        NOT NULL
);


CREATE TABLE TB_ENTREGA (
    ID_ENTREGA      SERIAL         PRIMARY KEY,
    CODIGO_PEDIDO   CHAR(20)       NOT NULL UNIQUE,
    ID_CLIENTE      INTEGER        NOT NULL,
    ID_PRODUTO      INTEGER        NOT NULL,
    DATA_ENVIO      DATE           NOT NULL,
    DATA_ENTREGA    DATE           NOT NULL,
    TRANSPORTADORA  VARCHAR(150)   NOT NULL,
    VALOR_FRETE     NUMERIC(10,2)  NOT NULL,

    CONSTRAINT FK_ENTREGA_CLIENTE
        FOREIGN KEY (ID_CLIENTE)
        REFERENCES TB_CLIENTE (ID_CLIENTE),

    CONSTRAINT FK_ENTREGA_PRODUTO
        FOREIGN KEY (ID_PRODUTO)
        REFERENCES TB_PRODUTO (ID_PRODUTO)
);
